# -*- coding: utf-8 -*-
"""du-doan-gia-nha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/ngquin102/d0358249f43d3d83ef5250b1f607444c/du-doan-gia-nha.ipynb
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/gdrive/MyDrive/Machine Learning'
!ls

df=pd.read_csv("homeprices.csv")
df

df.head()

df.to_csv("homeprices.csv",index=False)

x=df[['area']]
y=df['price']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=101)

print(x_train)

print(y_train)

from sklearn.linear_model import LinearRegression

lm=LinearRegression()

y_train=np.array([610000,565000,680000])

y_train=y_train.reshape(-1,1)
x_train=np.array([3200,3000,3600])

x_train=x_train.reshape(-1,1)

lm.fit(x_train, y_train)

x_test=np.array([x_test])
x_test=x_test.reshape(-1,1)
y_test=np.array([y_test])
y_test=y_test.reshape(-1,1)

predictions=lm.predict(x_test)
predictions

plt.scatter(y_test,predictions)

from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

metrics.explained_variance_score(y_test, predictions)

